### PR TITLE
Update add plugin node-canvas , return base64 format url

### PR DESCRIPTION
**Pull request by kiwilili**
The default browser, passing the {type: 'node'} parameter, will base64 format url

### CODE REVIEW

**Comment by oori** [comment]
Thanks a lot for the PR,  but right now I'd opt not to pull it as is.   Please see my comment at  https://github.com/ETCDEVTeam/hashicon/issues/23

1. Setting [node-canvas as dependency](https://github.com/ETCDEVTeam/hashicon/pull/24/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R62) will bloat this library for browser-only users,  that's why I suggested we allow an alternative `createCanvas function` rather then `type` as input.   This would also allow further flexibility for people with other custom canvas requirements.

2. hashicon returns a canvas, that should be consistent.   so I wouldn't return base64 for node and canvas for browser.     If one wants base64, they should `toDataURL()`, but maybe they'd want to `hashicon(hash).createPNGStream()` or [any other](https://github.com/Automattic/node-canvas#non-standard-apis) output node-canvas provides. 


So, I think it's better changing the `renderer` function to something like: `function renderer(hashValues, params, createCanvasFn)`  (and the relevant changes for the wrapping main.js).     I can do it in the next week (lack of time now). 

Thanks again for your PR!

**Comment by kiwilili** [comment]
Thank you for your reply, I think your suggestion will be more suitable for the purpose of using this project.

**Comment by justinmchase** [comment]
Hey, I really need to generate these images on the server also. Any word on this?

**Comment by oori** [comment]
Closing PR.  has been resolve in v0.3.0

**Pull request closed without merging**
